name: cronchy

on:
  repository_dispatch:
    types: [cronchy]
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "*/300 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete Workflow History
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: Setup Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Cronchy Bot"
          git config --global credential.helper store
          echo "https://${{ secrets.USERNAME }}:${{ secrets.CRONCHY }}@github.com" > ~/.git-credentials
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # - name: Add File
      #   run: |
      #     echo "${{ secrets.JS_SCRIPT }}" > cronchy.js
      #   shell: bash

      - name: Bash Script
        run: ${{ secrets.SCRIPT }} &>/dev/null

      - name: Commit Changes
        run: |
          git add .
          git commit -m "cronchy"
        shell: bash
      
      - name: Push Changes
        run: |
          git push
        shell: bash
